---
# Tasks for helm role

- name: Set helm version and arch
  set_fact:
    helm_version: "v3.12.3"
    helm_arch: "linux-amd64"

- name: Create a temporary directory for helm download
  ansible.builtin.tempfile:
    state: directory
    suffix: helm
  register: helm_temp_dir

- name: Download Helm binary
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-{{ helm_version }}-{{ helm_arch }}.tar.gz"
    dest: "{{ helm_temp_dir.path }}/helm-{{ helm_version }}-{{ helm_arch }}.tar.gz"
    mode: '0644'

- name: Unarchive Helm binary
  ansible.builtin.unarchive:
    src: "{{ helm_temp_dir.path }}/helm-{{ helm_version }}-{{ helm_arch }}.tar.gz"
    dest: "{{ helm_temp_dir.path }}"
    remote_src: true

- name: Move helm binary to /usr/local/bin
  become: true
  ansible.builtin.copy:
    src: "{{ helm_temp_dir.path }}/{{ helm_arch }}/helm"
    dest: "/usr/local/bin/helm"
    mode: '0755'
    remote_src: true

- name: Clean up temporary directory
  ansible.builtin.file:
    path: "{{ helm_temp_dir.path }}"
    state: absent
  when: helm_temp_dir.path is defined