---
- name: Deploy External Secrets operator and CRDs
  community.kubernetes.k8s:
    src: "{{ playbook_dir }}/files/apps/infrastructure/external-secrets.yaml"

- name: Wait for External Secrets CRD to be established
  community.kubernetes.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: clustersecretstores.external-secrets.io
  register: crd_info
  until: crd_info.resources | length > 0
  retries: 10
  delay: 15
