kubeconfig         = "~/.kube/config"
wazuh_helm_username = "REPLACE_WITH_YOUR_USERNAME"
wazuh_helm_password = "REPLACE_WITH_YOUR_PASSWORD"
target_revision    = "master"
environment        = "eksa-dev"
cert_manager_email = "REPLACE_WITH_YOUR_EMAIL"