kubeconfig         = "~/.kube/config"
wazuh_helm_username = "jB4mXCp70Pbq9VpY"
wazuh_helm_password = "XN9pqd9wonLcqX46"
target_revision    = "master"
environment        = "eksa-dev"
cert_manager_email = "admin@example.com"