---
# Tasks for cluster role

- name: 'Generate hardware.csv'
  ansible.builtin.template:
    src: ../../templates/hardware.csv.j2
    dest: '/tmp/hardware.csv'
    mode: '0644'

- name: 'Generate cluster.yaml'
  ansible.builtin.template:
    src: ../../templates/merged_cluster.yaml.j2
    dest: '/tmp/cluster.yaml'
    mode: '0644'

- name: 'Create EKS-A cluster'
  become: true
  ansible.builtin.command:
    cmd: 'eksctl anywhere create cluster -f /tmp/cluster.yaml --hardware-csv /tmp/hardware.csv'
  run_once: true