---
- name: Wait for Wazuh secrets to be created by external-secrets
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: '{{ item }}'
    namespace: wazuh
  register: secret_info
  until: secret_info.resources | length > 0
  retries: 20
  delay: 15
  loop:
    - ext-wazuh-root-ca-secrets
    - ext-wazuh-cluster-auth-secrets
    - ext-wazuh-indexer-secrets
    - ext-wazuh-api-credentials
    - ext-wazuh-dashboard-secrets

- name: Add Wazuh Helm repository
  community.kubernetes.helm_repository:
    name: wazuh
    repo_url: 'https://chartmuseum.wazuh.adorsys.team'
    repo_username: '{{ wazuh_helm_username }}'
    repo_password: '{{ wazuh_helm_password }}'
    state: present
    force_update: true
  no_log: true

- name: Deploy Wazuh from Helm chart
  kubernetes.core.helm:
    name: 'wazuh-{{ wazuh_environment }}'
    chart_ref: wazuh/wazuh-helm
    chart_version: '0.2.25'
    release_namespace: wazuh
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
