---
# For backward compatibility, this ExternalSecret can be used to access the CA certificate
# In a production environment, applications should directly use the secret created by cert-manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-root-ca-external-secret
  namespace: wazuh
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: wazuh-secret-store
    kind: ClusterSecretStore
  target:
    name: ext-wazuh-root-ca-secrets
    template:
      type: Opaque
      data:
        # In a real deployment with cert-manager, these would be populated from the cert-manager secret
        # For local development with the fake provider, we use static values
        root-ca.pem: "{{ .ca_crt }}"
        root-ca-key.pem: "{{ .ca_key }}"
  data:
    - secretKey: ca_crt
      remoteRef:
        key: dev/github/wazuh/root-ca
        property: ca.crt
    - secretKey: ca_key
      remoteRef:
        key: dev/github/wazuh/root-ca
        property: ca.key