---
- name: Gather facts and render EKS-A YAMLs
  hosts: cp,workers
  gather_facts: true
  become: true

  tasks:
    - name: Ensure build directory exists
      ansible.builtin.file:
        path: "{{ build_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Render merged_cluster.yaml
      ansible.builtin.template:
        src: ../templates/merged_cluster.yaml.j2
        dest: "{{ build_dir }}/cluster.yaml"
        mode: '0644'
      delegate_to: localhost
      run_once: true