---
# Tasks for image role
- name: Set variables for image role
  ansible.builtin.set_fact:
    local_eksa_os_path: ../eksa-node-images/
    remote_eksa_os_path: '{{ work_dir }}/os-images'
    image_server_port: '{{ image_server_port | default(8000) }}'

- name: Ensure OS image is present on remote machine
  block:
    - name: Ensure remote image directory exists
      ansible.builtin.file:
        path: '{{ remote_eksa_os_path }}'
        state: directory
        mode: '0755'

    - name: Copy built image to remote machine
      ansible.builtin.copy:
        src: '{{ local_eksa_os_path }}'
        dest: '{{ remote_eksa_os_path }}'
        mode: '0644'

    - name: Start Python HTTP server to serve the image
      ansible.builtin.shell: |
        # Check if server is already running
        if ! lsof -i:{{ image_server_port }} | grep python3; then
          python3 -m http.server {{ image_server_port }} --directory "{{ remote_eksa_os_path }}" > /var/log/image-server.log 2>&1 &
        fi
      args:
        executable: /bin/bash
      async: 0
      poll: 0
  become: true
