---
- name: Configure VM and Create EKS-A Cluster
  hosts: eksa_vms
  become: true
  roles:
    - role: common
    - role: docker
      when: eksa_provider == 'docker'
    - role: eksa
    - role: cert_manager
    - role: external_secrets
    - role: kube_manifests
    - role: wazuh