---
- name: Setup Admin VM for EKS Anywhere
  hosts: admin
  become: true
  pre_tasks:
    - name: Set working directory
      set_fact:
        work_dir: /opt/eksa

    - name: Fail if REGISTRY_PASSWORD or REGISTRY_USERNAME is not set
      fail:
        msg: 'The REGISTRY_PASSWORD or REGISTRY_USERNAME environment variable is not set. Please set it before running the playbook.'
      when: lookup('env', 'REGISTRY_PASSWORD') == '' or lookup('env', 'REGISTRY_USERNAME') == ''

    - name: Set registry password from environment variable
      set_fact:
        registry_username: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
        registry_password: "{{ lookup('env', 'REGISTRY_PASSWORD') }}"
      tags:
        - registry
        - registry-auth
        - registry-htpasswd
    
    - name: Set airgapped_environment fact if not defined
      set_fact:
        airgapped_environment: false
      when: airgapped_environment is not defined

    - name: Flush handlers
      meta: flush_handlers
      when: airgapped_environment
  roles:
    - role: common
    - role: ntp
    - role: docker
    - role: helm
    - role: eksctl
    - role: image
    - role: airgapped
      when: airgapped_environment
    - role: cluster
    - role: gateway
      when: not airgapped_environment
