---
- name: Gather facts from CP and Worker nodes
  hosts: cp, workers
  gather_facts: true
  tasks:
    - name: Ensure facts are gathered
      ansible.builtin.setup:
        gather_subset:
          - network

- name: Setup Admin VM for EKS Anywhere
  hosts: admin
  become: true
  roles:
    - role: common
    - role: docker
    - role: eksa
